### ISSUE TITLE
Crash when receiving same VC multiple times

### ISSUE THREAD

**Issue by celinenilla** [idpass/inji#76]
**Describe the bug**
When sharing the same VC a second time the receiving device will crash after accepting the request. The first share works without issues

**To Reproduce**
1. Share VC1 from device A to device B
2. Verify that VC is correctly received
3. Share VC1 from device A to device B
4. After clicking "Accept request and receive VC" the receiving device will crash

**Expected behavior**
VC should be received multiple times

**Occurred on build:**
0.2.1-beta2-newlogic_20220303_1026.apk

**Comment by pmigueld** [comment]
Log from Firebase Crashlytics:

https://console.firebase.google.com/project/mosip-resident-app/crashlytics/app/android:io.mosip.residentapp/issues/ae12e08275f7310db29992f1ef9776f6?time=last-seven-days&sessionEventKey=6221C1C2015D00010B072E26A536DCE6_1649592368311779473

The issue seems to be around the routing logic. I'm looking into a fix right now.

**Comment by celinenilla** [comment]
Tested on 0.2.1 RC3. Working as expected.
